#!/usr/bin/env python3
"""
Opt-in Hybridizer porting log.

Appends each user prompt to porting-to-hybridizer.md at the project root,
but ONLY if .hybridizer-log-enabled exists at the project root.
Toggle with /hybridizer-log on|off.

Off by default. Exits 0 silently when the flag file is absent so the hook
is invisible to users who haven't opted in.
"""
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0  # malformed input — fail silently rather than block the prompt

    project_dir = os.environ.get("CLAUDE_PROJECT_DIR") or payload.get("cwd")
    if not project_dir:
        return 0

    flag = Path(project_dir) / ".hybridizer-log-enabled"
    if not flag.exists():
        return 0

    prompt = payload.get("prompt", "").strip()
    if not prompt:
        return 0

    log = Path(project_dir) / "porting-to-hybridizer.md"
    timestamp = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")

    header = (
        "# Hybridizer porting log\n"
        "\n"
        "Auto-generated by the `hybridizer-port` Claude Code plugin.\n"
        "Toggle with `/hybridizer-log on|off`.\n"
        "\n"
    )

    with log.open("a", encoding="utf-8") as f:
        if log.stat().st_size == 0:
            f.write(header)
        f.write(f"\n## {timestamp}\n\n{prompt}\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
